baseURL: https://handbook.leomosia.com/
locale: en-US
title: Leo Mosia Handbook
theme: docsy

enableGitInfo: true
enableRobotsTXT: true
pluralizeListTitles: false

params:
  title: The Leo Mosia Handbook
  description: The operating manual for the Leo Mosia ecosystem.
  copyright: Leo Mosia
  github_repo: https://github.com/leomosia/handbook
  github_branch: master
  github_subdir: ""
  offlineSearch: true
  ui:
    sidebar_menu_compact: false
    sidebar_menu_foldable: true
    sidebar_cache_limit: 1000
    navbar_logo: true
    footer_about_enable: false
    showLightDarkModeMenu: false
  links:
    user: []
    developer: []

menu:
  main:
    - weight: 10
      name: leomosia.com
      url: https://leomosia.com/

markup:
  goldmark:
    renderer:
      unsafe: true
    parser:
      attribute:
        block: true
  highlight:
    noClasses: false
  tableOfContents:
    startLevel: 2
    endLevel: 4
    ordered: false

outputs:
  home:
    - HTML
    - RSS
  section:
    - HTML
    - RSS

security:
  funcs:
    getenv:
      - ^HUGO_
      - ^HANDBOOK_
