name: Handbook

on:
  pull_request:
  push:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build Docker image
        run: docker compose build

      - name: Check handbook
        run: docker compose run --rm handbook npm run check
